# Generated by Django 3.2.3 on 2021-05-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('year', models.IntegerField()),
                ('genre', models.TextField(max_length=100)),
                ('rating', models.FloatField(default=0.0)),
                ('poster', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
